## PRÁCTICA 1
Laboratorio de bioseñales y sistemas

Integrantes:

Luisa María Martínez Muelas
Carolina Taborda Vargas

### Resumen


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


## Multiplicación escalar de dos vectores

In [9]:
#Creación de vectores
a= np.array([3.1,1, -0.5, -3.2, 6])
b=np.array([1, 3, 2.2, 5.1, 1])

#Multiplicación escalar de los vectores
mul=a@b
print("La multiplicación escalar de los vectores es:\n", mul)

La multiplicación escalar de los vectores es:
 -5.320000000000002


Para realizar la multiplicación escalar de ambos vectores, primero se debe convertir la lista a un arreglo de numpy para que la multiplicación sea elemento a elemento y en forma matricial. Luego, para la multiplicación, se crea una variable en la que se llame a los vectores operándolos con el símbolo @

## Creación de matriz

In [8]:
#Construcción de matriz
A=[
    [2,-1,-3],
    [4,1.5,-2.5],
    [7.3,-0.9,0.2]
]
#Matriz transpuesta
AT=np.transpose(A)
print("La matriz transpuesta es:\n", AT)



La matriz transpuesta es:
 [[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


#### Teoría

#### Conclusiones